//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulService) DeepCopyInto(out *ConsulService) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulService.
func (in *ConsulService) DeepCopy() *ConsulService {
	if in == nil {
		return nil
	}
	out := new(ConsulService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8SService) DeepCopyInto(out *K8SService) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SService.
func (in *K8SService) DeepCopy() *K8SService {
	if in == nil {
		return nil
	}
	out := new(K8SService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPool) DeepCopyInto(out *OriginPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPool.
func (in *OriginPool) DeepCopy() *OriginPool {
	if in == nil {
		return nil
	}
	out := new(OriginPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OriginPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPoolList) DeepCopyInto(out *OriginPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OriginPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPoolList.
func (in *OriginPoolList) DeepCopy() *OriginPoolList {
	if in == nil {
		return nil
	}
	out := new(OriginPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OriginPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPoolSpec) DeepCopyInto(out *OriginPoolSpec) {
	*out = *in
	if in.OriginServers != nil {
		in, out := &in.OriginServers, &out.OriginServers
		*out = make([]OriginServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HealthChecks != nil {
		in, out := &in.HealthChecks, &out.HealthChecks
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
	if in.UseTLS != nil {
		in, out := &in.UseTLS, &out.UseTLS
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.NoTLS != nil {
		in, out := &in.NoTLS, &out.NoTLS
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPoolSpec.
func (in *OriginPoolSpec) DeepCopy() *OriginPoolSpec {
	if in == nil {
		return nil
	}
	out := new(OriginPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPoolStatus) DeepCopyInto(out *OriginPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPoolStatus.
func (in *OriginPoolStatus) DeepCopy() *OriginPoolStatus {
	if in == nil {
		return nil
	}
	out := new(OriginPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginServer) DeepCopyInto(out *OriginServer) {
	*out = *in
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(PublicIP)
		**out = **in
	}
	if in.PublicName != nil {
		in, out := &in.PublicName, &out.PublicName
		*out = new(PublicName)
		**out = **in
	}
	if in.PrivateIP != nil {
		in, out := &in.PrivateIP, &out.PrivateIP
		*out = new(PrivateIP)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateName != nil {
		in, out := &in.PrivateName, &out.PrivateName
		*out = new(PrivateName)
		(*in).DeepCopyInto(*out)
	}
	if in.K8SService != nil {
		in, out := &in.K8SService, &out.K8SService
		*out = new(K8SService)
		(*in).DeepCopyInto(*out)
	}
	if in.ConsulService != nil {
		in, out := &in.ConsulService, &out.ConsulService
		*out = new(ConsulService)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginServer.
func (in *OriginServer) DeepCopy() *OriginServer {
	if in == nil {
		return nil
	}
	out := new(OriginServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateIP) DeepCopyInto(out *PrivateIP) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateIP.
func (in *PrivateIP) DeepCopy() *PrivateIP {
	if in == nil {
		return nil
	}
	out := new(PrivateIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateName) DeepCopyInto(out *PrivateName) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateName.
func (in *PrivateName) DeepCopy() *PrivateName {
	if in == nil {
		return nil
	}
	out := new(PrivateName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicIP) DeepCopyInto(out *PublicIP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicIP.
func (in *PublicIP) DeepCopy() *PublicIP {
	if in == nil {
		return nil
	}
	out := new(PublicIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicName) DeepCopyInto(out *PublicName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicName.
func (in *PublicName) DeepCopy() *PublicName {
	if in == nil {
		return nil
	}
	out := new(PublicName)
	in.DeepCopyInto(out)
	return out
}
