//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDefinition) DeepCopyInto(out *APIDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDefinition.
func (in *APIDefinition) DeepCopy() *APIDefinition {
	if in == nil {
		return nil
	}
	out := new(APIDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDefinitionList) DeepCopyInto(out *APIDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDefinitionList.
func (in *APIDefinitionList) DeepCopy() *APIDefinitionList {
	if in == nil {
		return nil
	}
	out := new(APIDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDefinitionSpec) DeepCopyInto(out *APIDefinitionSpec) {
	*out = *in
	if in.SwaggerSpecs != nil {
		in, out := &in.SwaggerSpecs, &out.SwaggerSpecs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.APIInventoryInclusionList != nil {
		in, out := &in.APIInventoryInclusionList, &out.APIInventoryInclusionList
		*out = make([]APIOperation, len(*in))
		copy(*out, *in)
	}
	if in.APIInventoryExclusionList != nil {
		in, out := &in.APIInventoryExclusionList, &out.APIInventoryExclusionList
		*out = make([]APIOperation, len(*in))
		copy(*out, *in)
	}
	if in.NonAPIEndpoints != nil {
		in, out := &in.NonAPIEndpoints, &out.NonAPIEndpoints
		*out = make([]APIOperation, len(*in))
		copy(*out, *in)
	}
	if in.MixedSchemaOrigin != nil {
		in, out := &in.MixedSchemaOrigin, &out.MixedSchemaOrigin
		*out = new(EmptyObject)
		**out = **in
	}
	if in.StrictSchemaOrigin != nil {
		in, out := &in.StrictSchemaOrigin, &out.StrictSchemaOrigin
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDefinitionSpec.
func (in *APIDefinitionSpec) DeepCopy() *APIDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(APIDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDefinitionStatus) DeepCopyInto(out *APIDefinitionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDefinitionStatus.
func (in *APIDefinitionStatus) DeepCopy() *APIDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(APIDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIOperation) DeepCopyInto(out *APIOperation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIOperation.
func (in *APIOperation) DeepCopy() *APIOperation {
	if in == nil {
		return nil
	}
	out := new(APIOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASNList) DeepCopyInto(out *ASNList) {
	*out = *in
	if in.ASNumbers != nil {
		in, out := &in.ASNumbers, &out.ASNumbers
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASNList.
func (in *ASNList) DeepCopy() *ASNList {
	if in == nil {
		return nil
	}
	out := new(ASNList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASNMatcher) DeepCopyInto(out *ASNMatcher) {
	*out = *in
	if in.ASNumbers != nil {
		in, out := &in.ASNumbers, &out.ASNumbers
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASNMatcher.
func (in *ASNMatcher) DeepCopy() *ASNMatcher {
	if in == nil {
		return nil
	}
	out := new(ASNMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveServicePoliciesConfig) DeepCopyInto(out *ActiveServicePoliciesConfig) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveServicePoliciesConfig.
func (in *ActiveServicePoliciesConfig) DeepCopy() *ActiveServicePoliciesConfig {
	if in == nil {
		return nil
	}
	out := new(ActiveServicePoliciesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiseCustom) DeepCopyInto(out *AdvertiseCustom) {
	*out = *in
	if in.AdvertiseWhere != nil {
		in, out := &in.AdvertiseWhere, &out.AdvertiseWhere
		*out = make([]AdvertiseWhere, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiseCustom.
func (in *AdvertiseCustom) DeepCopy() *AdvertiseCustom {
	if in == nil {
		return nil
	}
	out := new(AdvertiseCustom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiseOnPublic) DeepCopyInto(out *AdvertiseOnPublic) {
	*out = *in
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(ObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiseOnPublic.
func (in *AdvertiseOnPublic) DeepCopy() *AdvertiseOnPublic {
	if in == nil {
		return nil
	}
	out := new(AdvertiseOnPublic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiseSite) DeepCopyInto(out *AdvertiseSite) {
	*out = *in
	out.Site = in.Site
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiseSite.
func (in *AdvertiseSite) DeepCopy() *AdvertiseSite {
	if in == nil {
		return nil
	}
	out := new(AdvertiseSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiseVirtualNetwork) DeepCopyInto(out *AdvertiseVirtualNetwork) {
	*out = *in
	if in.DefaultVIP != nil {
		in, out := &in.DefaultVIP, &out.DefaultVIP
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiseVirtualNetwork.
func (in *AdvertiseVirtualNetwork) DeepCopy() *AdvertiseVirtualNetwork {
	if in == nil {
		return nil
	}
	out := new(AdvertiseVirtualNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiseWhere) DeepCopyInto(out *AdvertiseWhere) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(AdvertiseSite)
		**out = **in
	}
	if in.VirtualSite != nil {
		in, out := &in.VirtualSite, &out.VirtualSite
		*out = new(AdvertiseSite)
		**out = **in
	}
	if in.VirtualNetwork != nil {
		in, out := &in.VirtualNetwork, &out.VirtualNetwork
		*out = new(AdvertiseVirtualNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.UseDefaultPort != nil {
		in, out := &in.UseDefaultPort, &out.UseDefaultPort
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiseWhere.
func (in *AdvertiseWhere) DeepCopy() *AdvertiseWhere {
	if in == nil {
		return nil
	}
	out := new(AdvertiseWhere)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedResponseCodes) DeepCopyInto(out *AllowedResponseCodes) {
	*out = *in
	if in.ResponseCode != nil {
		in, out := &in.ResponseCode, &out.ResponseCode
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedResponseCodes.
func (in *AllowedResponseCodes) DeepCopy() *AllowedResponseCodes {
	if in == nil {
		return nil
	}
	out := new(AllowedResponseCodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationEntry) DeepCopyInto(out *AnonymizationEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationEntry.
func (in *AnonymizationEntry) DeepCopy() *AnonymizationEntry {
	if in == nil {
		return nil
	}
	out := new(AnonymizationEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppFirewall) DeepCopyInto(out *AppFirewall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppFirewall.
func (in *AppFirewall) DeepCopy() *AppFirewall {
	if in == nil {
		return nil
	}
	out := new(AppFirewall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppFirewall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppFirewallList) DeepCopyInto(out *AppFirewallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppFirewall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppFirewallList.
func (in *AppFirewallList) DeepCopy() *AppFirewallList {
	if in == nil {
		return nil
	}
	out := new(AppFirewallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppFirewallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppFirewallSpec) DeepCopyInto(out *AppFirewallSpec) {
	*out = *in
	if in.DefaultDetectionSettings != nil {
		in, out := &in.DefaultDetectionSettings, &out.DefaultDetectionSettings
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DetectionSettings != nil {
		in, out := &in.DetectionSettings, &out.DetectionSettings
		*out = new(DetectionSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(EmptyObject)
		**out = **in
	}
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UseDefaultBlockingPage != nil {
		in, out := &in.UseDefaultBlockingPage, &out.UseDefaultBlockingPage
		*out = new(EmptyObject)
		**out = **in
	}
	if in.BlockingPage != nil {
		in, out := &in.BlockingPage, &out.BlockingPage
		*out = new(BlockingPage)
		**out = **in
	}
	if in.AllowAllResponseCodes != nil {
		in, out := &in.AllowAllResponseCodes, &out.AllowAllResponseCodes
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AllowedResponseCodes != nil {
		in, out := &in.AllowedResponseCodes, &out.AllowedResponseCodes
		*out = new(AllowedResponseCodes)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultBotSetting != nil {
		in, out := &in.DefaultBotSetting, &out.DefaultBotSetting
		*out = new(EmptyObject)
		**out = **in
	}
	if in.BotProtectionSetting != nil {
		in, out := &in.BotProtectionSetting, &out.BotProtectionSetting
		*out = new(BotProtectionSetting)
		**out = **in
	}
	if in.DefaultAnonymization != nil {
		in, out := &in.DefaultAnonymization, &out.DefaultAnonymization
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DisableAnonymization != nil {
		in, out := &in.DisableAnonymization, &out.DisableAnonymization
		*out = new(EmptyObject)
		**out = **in
	}
	if in.CustomAnonymization != nil {
		in, out := &in.CustomAnonymization, &out.CustomAnonymization
		*out = new(CustomAnonymization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppFirewallSpec.
func (in *AppFirewallSpec) DeepCopy() *AppFirewallSpec {
	if in == nil {
		return nil
	}
	out := new(AppFirewallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppFirewallStatus) DeepCopyInto(out *AppFirewallStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppFirewallStatus.
func (in *AppFirewallStatus) DeepCopy() *AppFirewallStatus {
	if in == nil {
		return nil
	}
	out := new(AppFirewallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttackType) DeepCopyInto(out *AttackType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttackType.
func (in *AttackType) DeepCopy() *AttackType {
	if in == nil {
		return nil
	}
	out := new(AttackType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttackTypeSettings) DeepCopyInto(out *AttackTypeSettings) {
	*out = *in
	if in.DisabledAttackTypes != nil {
		in, out := &in.DisabledAttackTypes, &out.DisabledAttackTypes
		*out = make([]AttackType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttackTypeSettings.
func (in *AttackTypeSettings) DeepCopy() *AttackTypeSettings {
	if in == nil {
		return nil
	}
	out := new(AttackTypeSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockingPage) DeepCopyInto(out *BlockingPage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockingPage.
func (in *BlockingPage) DeepCopy() *BlockingPage {
	if in == nil {
		return nil
	}
	out := new(BlockingPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotDefenseConfig) DeepCopyInto(out *BotDefenseConfig) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(BotDefensePolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotDefenseConfig.
func (in *BotDefenseConfig) DeepCopy() *BotDefenseConfig {
	if in == nil {
		return nil
	}
	out := new(BotDefenseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotDefensePolicy) DeepCopyInto(out *BotDefensePolicy) {
	*out = *in
	if in.ProtectedAppEndpoints != nil {
		in, out := &in.ProtectedAppEndpoints, &out.ProtectedAppEndpoints
		*out = make([]ProtectedAppEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JSInsertionRules != nil {
		in, out := &in.JSInsertionRules, &out.JSInsertionRules
		*out = new(JSInsertionRules)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableMobileSDK != nil {
		in, out := &in.DisableMobileSDK, &out.DisableMobileSDK
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotDefensePolicy.
func (in *BotDefensePolicy) DeepCopy() *BotDefensePolicy {
	if in == nil {
		return nil
	}
	out := new(BotDefensePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotProtectionSetting) DeepCopyInto(out *BotProtectionSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotProtectionSetting.
func (in *BotProtectionSetting) DeepCopy() *BotProtectionSetting {
	if in == nil {
		return nil
	}
	out := new(BotProtectionSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptchaChallengeConfig) DeepCopyInto(out *CaptchaChallengeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptchaChallengeConfig.
func (in *CaptchaChallengeConfig) DeepCopy() *CaptchaChallengeConfig {
	if in == nil {
		return nil
	}
	out := new(CaptchaChallengeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificate) DeepCopyInto(out *Certificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificate.
func (in *Certificate) DeepCopy() *Certificate {
	if in == nil {
		return nil
	}
	out := new(Certificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Certificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateList) DeepCopyInto(out *CertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Certificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateList.
func (in *CertificateList) DeepCopy() *CertificateList {
	if in == nil {
		return nil
	}
	out := new(CertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificatePrivKey) DeepCopyInto(out *CertificatePrivKey) {
	*out = *in
	if in.ClearSecretInfo != nil {
		in, out := &in.ClearSecretInfo, &out.ClearSecretInfo
		*out = new(ClearSecretInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificatePrivKey.
func (in *CertificatePrivKey) DeepCopy() *CertificatePrivKey {
	if in == nil {
		return nil
	}
	out := new(CertificatePrivKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpec) DeepCopyInto(out *CertificateSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.CustomHashAlgorithms != nil {
		in, out := &in.CustomHashAlgorithms, &out.CustomHashAlgorithms
		*out = new(CustomHashAlgorithms)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableOcspStapling != nil {
		in, out := &in.DisableOcspStapling, &out.DisableOcspStapling
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UseSystemDefaults != nil {
		in, out := &in.UseSystemDefaults, &out.UseSystemDefaults
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpec.
func (in *CertificateSpec) DeepCopy() *CertificateSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatus) DeepCopyInto(out *CertificateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatus.
func (in *CertificateStatus) DeepCopy() *CertificateStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChallengeRule) DeepCopyInto(out *ChallengeRule) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(ChallengeRuleSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChallengeRule.
func (in *ChallengeRule) DeepCopy() *ChallengeRule {
	if in == nil {
		return nil
	}
	out := new(ChallengeRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChallengeRuleList) DeepCopyInto(out *ChallengeRuleList) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ChallengeRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChallengeRuleList.
func (in *ChallengeRuleList) DeepCopy() *ChallengeRuleList {
	if in == nil {
		return nil
	}
	out := new(ChallengeRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChallengeRuleSpec) DeepCopyInto(out *ChallengeRuleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChallengeRuleSpec.
func (in *ChallengeRuleSpec) DeepCopy() *ChallengeRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ChallengeRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClearSecretInfo) DeepCopyInto(out *ClearSecretInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearSecretInfo.
func (in *ClearSecretInfo) DeepCopy() *ClearSecretInfo {
	if in == nil {
		return nil
	}
	out := new(ClearSecretInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulService) DeepCopyInto(out *ConsulService) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
	if in.VirtualSite != nil {
		in, out := &in.VirtualSite, &out.VirtualSite
		*out = new(ObjectRef)
		**out = **in
	}
	if in.InsideNetwork != nil {
		in, out := &in.InsideNetwork, &out.InsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
	if in.OutsideNetwork != nil {
		in, out := &in.OutsideNetwork, &out.OutsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulService.
func (in *ConsulService) DeepCopy() *ConsulService {
	if in == nil {
		return nil
	}
	out := new(ConsulService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CookieForHashing) DeepCopyInto(out *CookieForHashing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CookieForHashing.
func (in *CookieForHashing) DeepCopy() *CookieForHashing {
	if in == nil {
		return nil
	}
	out := new(CookieForHashing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CookieStickinessConfig) DeepCopyInto(out *CookieStickinessConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CookieStickinessConfig.
func (in *CookieStickinessConfig) DeepCopy() *CookieStickinessConfig {
	if in == nil {
		return nil
	}
	out := new(CookieStickinessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAnonymization) DeepCopyInto(out *CustomAnonymization) {
	*out = *in
	if in.AnonymizationConfig != nil {
		in, out := &in.AnonymizationConfig, &out.AnonymizationConfig
		*out = make([]AnonymizationEntry, len(*in))
		copy(*out, *in)
	}
	if in.SpecificDomains != nil {
		in, out := &in.SpecificDomains, &out.SpecificDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAnonymization.
func (in *CustomAnonymization) DeepCopy() *CustomAnonymization {
	if in == nil {
		return nil
	}
	out := new(CustomAnonymization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHashAlgorithms) DeepCopyInto(out *CustomHashAlgorithms) {
	*out = *in
	if in.HashAlgorithms != nil {
		in, out := &in.HashAlgorithms, &out.HashAlgorithms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHashAlgorithms.
func (in *CustomHashAlgorithms) DeepCopy() *CustomHashAlgorithms {
	if in == nil {
		return nil
	}
	out := new(CustomHashAlgorithms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomTLSSecurity) DeepCopyInto(out *CustomTLSSecurity) {
	*out = *in
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomTLSSecurity.
func (in *CustomTLSSecurity) DeepCopy() *CustomTLSSecurity {
	if in == nil {
		return nil
	}
	out := new(CustomTLSSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionSettings) DeepCopyInto(out *DetectionSettings) {
	*out = *in
	if in.SignatureSelectionSetting != nil {
		in, out := &in.SignatureSelectionSetting, &out.SignatureSelectionSetting
		*out = new(SignatureSelectionSetting)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableSuppression != nil {
		in, out := &in.EnableSuppression, &out.EnableSuppression
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DisableSuppression != nil {
		in, out := &in.DisableSuppression, &out.DisableSuppression
		*out = new(EmptyObject)
		**out = **in
	}
	if in.EnableThreatCampaigns != nil {
		in, out := &in.EnableThreatCampaigns, &out.EnableThreatCampaigns
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DisableThreatCampaigns != nil {
		in, out := &in.DisableThreatCampaigns, &out.DisableThreatCampaigns
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionSettings.
func (in *DetectionSettings) DeepCopy() *DetectionSettings {
	if in == nil {
		return nil
	}
	out := new(DetectionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredAPISettings) DeepCopyInto(out *DiscoveredAPISettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredAPISettings.
func (in *DiscoveredAPISettings) DeepCopy() *DiscoveredAPISettings {
	if in == nil {
		return nil
	}
	out := new(DiscoveredAPISettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredOrigin) DeepCopyInto(out *DiscoveredOrigin) {
	*out = *in
	out.Resource = in.Resource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredOrigin.
func (in *DiscoveredOrigin) DeepCopy() *DiscoveredOrigin {
	if in == nil {
		return nil
	}
	out := new(DiscoveredOrigin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmptyObject) DeepCopyInto(out *EmptyObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmptyObject.
func (in *EmptyObject) DeepCopy() *EmptyObject {
	if in == nil {
		return nil
	}
	out := new(EmptyObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableAPIDiscoveryConfig) DeepCopyInto(out *EnableAPIDiscoveryConfig) {
	*out = *in
	if in.EnableLearnFromRedirectTraffic != nil {
		in, out := &in.EnableLearnFromRedirectTraffic, &out.EnableLearnFromRedirectTraffic
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DisableLearnFromRedirectTraffic != nil {
		in, out := &in.DisableLearnFromRedirectTraffic, &out.DisableLearnFromRedirectTraffic
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DefaultAPIAuthDiscovery != nil {
		in, out := &in.DefaultAPIAuthDiscovery, &out.DefaultAPIAuthDiscovery
		*out = new(EmptyObject)
		**out = **in
	}
	if in.APICrawler != nil {
		in, out := &in.APICrawler, &out.APICrawler
		*out = new(ObjectRef)
		**out = **in
	}
	if in.APIDiscoveryFromCodeScan != nil {
		in, out := &in.APIDiscoveryFromCodeScan, &out.APIDiscoveryFromCodeScan
		*out = new(ObjectRef)
		**out = **in
	}
	if in.DiscoveredAPISettings != nil {
		in, out := &in.DiscoveredAPISettings, &out.DiscoveredAPISettings
		*out = new(DiscoveredAPISettings)
		**out = **in
	}
	if in.SensitiveDataDetectionRules != nil {
		in, out := &in.SensitiveDataDetectionRules, &out.SensitiveDataDetectionRules
		*out = new(SensitiveDataDetectionRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableAPIDiscoveryConfig.
func (in *EnableAPIDiscoveryConfig) DeepCopy() *EnableAPIDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(EnableAPIDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableIPReputationConfig) DeepCopyInto(out *EnableIPReputationConfig) {
	*out = *in
	if in.IPThreatCategories != nil {
		in, out := &in.IPThreatCategories, &out.IPThreatCategories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableIPReputationConfig.
func (in *EnableIPReputationConfig) DeepCopy() *EnableIPReputationConfig {
	if in == nil {
		return nil
	}
	out := new(EnableIPReputationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPConfig) DeepCopyInto(out *HTTPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPConfig.
func (in *HTTPConfig) DeepCopy() *HTTPConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHealthCheckSpec) DeepCopyInto(out *HTTPHealthCheckSpec) {
	*out = *in
	if in.ExpectedStatusCodes != nil {
		in, out := &in.ExpectedStatusCodes, &out.ExpectedStatusCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHealthCheckSpec.
func (in *HTTPHealthCheckSpec) DeepCopy() *HTTPHealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPHealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPLoadBalancer) DeepCopyInto(out *HTTPLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPLoadBalancer.
func (in *HTTPLoadBalancer) DeepCopy() *HTTPLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(HTTPLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPLoadBalancerList) DeepCopyInto(out *HTTPLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPLoadBalancerList.
func (in *HTTPLoadBalancerList) DeepCopy() *HTTPLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(HTTPLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPLoadBalancerSpec) DeepCopyInto(out *HTTPLoadBalancerSpec) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultRoutePools != nil {
		in, out := &in.DefaultRoutePools, &out.DefaultRoutePools
		*out = make([]RoutePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPConfig)
		**out = **in
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(HTTPSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSAutoCert != nil {
		in, out := &in.HTTPSAutoCert, &out.HTTPSAutoCert
		*out = new(HTTPSAutoCertConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableWAF != nil {
		in, out := &in.DisableWAF, &out.DisableWAF
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AppFirewall != nil {
		in, out := &in.AppFirewall, &out.AppFirewall
		*out = new(ObjectRef)
		**out = **in
	}
	if in.DisableBotDefense != nil {
		in, out := &in.DisableBotDefense, &out.DisableBotDefense
		*out = new(EmptyObject)
		**out = **in
	}
	if in.BotDefense != nil {
		in, out := &in.BotDefense, &out.BotDefense
		*out = new(BotDefenseConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableAPIDiscovery != nil {
		in, out := &in.DisableAPIDiscovery, &out.DisableAPIDiscovery
		*out = new(EmptyObject)
		**out = **in
	}
	if in.EnableAPIDiscovery != nil {
		in, out := &in.EnableAPIDiscovery, &out.EnableAPIDiscovery
		*out = new(EnableAPIDiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableIPReputation != nil {
		in, out := &in.DisableIPReputation, &out.DisableIPReputation
		*out = new(EmptyObject)
		**out = **in
	}
	if in.EnableIPReputation != nil {
		in, out := &in.EnableIPReputation, &out.EnableIPReputation
		*out = new(EnableIPReputationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableRateLimit != nil {
		in, out := &in.DisableRateLimit, &out.DisableRateLimit
		*out = new(EmptyObject)
		**out = **in
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NoChallenge != nil {
		in, out := &in.NoChallenge, &out.NoChallenge
		*out = new(EmptyObject)
		**out = **in
	}
	if in.JSChallenge != nil {
		in, out := &in.JSChallenge, &out.JSChallenge
		*out = new(JSChallengeConfig)
		**out = **in
	}
	if in.CaptchaChallenge != nil {
		in, out := &in.CaptchaChallenge, &out.CaptchaChallenge
		*out = new(CaptchaChallengeConfig)
		**out = **in
	}
	if in.PolicyBasedChallenge != nil {
		in, out := &in.PolicyBasedChallenge, &out.PolicyBasedChallenge
		*out = new(PolicyBasedChallengeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RoundRobin != nil {
		in, out := &in.RoundRobin, &out.RoundRobin
		*out = new(EmptyObject)
		**out = **in
	}
	if in.LeastActive != nil {
		in, out := &in.LeastActive, &out.LeastActive
		*out = new(EmptyObject)
		**out = **in
	}
	if in.Random != nil {
		in, out := &in.Random, &out.Random
		*out = new(EmptyObject)
		**out = **in
	}
	if in.SourceIPStickiness != nil {
		in, out := &in.SourceIPStickiness, &out.SourceIPStickiness
		*out = new(EmptyObject)
		**out = **in
	}
	if in.CookieStickiness != nil {
		in, out := &in.CookieStickiness, &out.CookieStickiness
		*out = new(CookieStickinessConfig)
		**out = **in
	}
	if in.RingHash != nil {
		in, out := &in.RingHash, &out.RingHash
		*out = new(RingHashConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvertiseOnPublicDefaultVIP != nil {
		in, out := &in.AdvertiseOnPublicDefaultVIP, &out.AdvertiseOnPublicDefaultVIP
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AdvertiseOnPublic != nil {
		in, out := &in.AdvertiseOnPublic, &out.AdvertiseOnPublic
		*out = new(AdvertiseOnPublic)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvertiseCustom != nil {
		in, out := &in.AdvertiseCustom, &out.AdvertiseCustom
		*out = new(AdvertiseCustom)
		(*in).DeepCopyInto(*out)
	}
	if in.DoNotAdvertise != nil {
		in, out := &in.DoNotAdvertise, &out.DoNotAdvertise
		*out = new(EmptyObject)
		**out = **in
	}
	if in.ServicePoliciesFromNamespace != nil {
		in, out := &in.ServicePoliciesFromNamespace, &out.ServicePoliciesFromNamespace
		*out = new(EmptyObject)
		**out = **in
	}
	if in.ActiveServicePolicies != nil {
		in, out := &in.ActiveServicePolicies, &out.ActiveServicePolicies
		*out = new(ActiveServicePoliciesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NoServicePolicies != nil {
		in, out := &in.NoServicePolicies, &out.NoServicePolicies
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UserIDClientIP != nil {
		in, out := &in.UserIDClientIP, &out.UserIDClientIP
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPLoadBalancerSpec.
func (in *HTTPLoadBalancerSpec) DeepCopy() *HTTPLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPLoadBalancerStatus) DeepCopyInto(out *HTTPLoadBalancerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPLoadBalancerStatus.
func (in *HTTPLoadBalancerStatus) DeepCopy() *HTTPLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPMethodMatcher) DeepCopyInto(out *HTTPMethodMatcher) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPMethodMatcher.
func (in *HTTPMethodMatcher) DeepCopy() *HTTPMethodMatcher {
	if in == nil {
		return nil
	}
	out := new(HTTPMethodMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSAutoCertConfig) DeepCopyInto(out *HTTPSAutoCertConfig) {
	*out = *in
	if in.NoMTLS != nil {
		in, out := &in.NoMTLS, &out.NoMTLS
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UseMTLS != nil {
		in, out := &in.UseMTLS, &out.UseMTLS
		*out = new(UseMTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSAutoCertConfig.
func (in *HTTPSAutoCertConfig) DeepCopy() *HTTPSAutoCertConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPSAutoCertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSConfig) DeepCopyInto(out *HTTPSConfig) {
	*out = *in
	if in.TLSCertificates != nil {
		in, out := &in.TLSCertificates, &out.TLSCertificates
		*out = make([]TLSCertificateRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultSecurity != nil {
		in, out := &in.DefaultSecurity, &out.DefaultSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.LowSecurity != nil {
		in, out := &in.LowSecurity, &out.LowSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.MediumSecurity != nil {
		in, out := &in.MediumSecurity, &out.MediumSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.CustomSecurity != nil {
		in, out := &in.CustomSecurity, &out.CustomSecurity
		*out = new(CustomTLSSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.NoMTLS != nil {
		in, out := &in.NoMTLS, &out.NoMTLS
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UseMTLS != nil {
		in, out := &in.UseMTLS, &out.UseMTLS
		*out = new(UseMTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSConfig.
func (in *HTTPSConfig) DeepCopy() *HTTPSConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HashPolicy) DeepCopyInto(out *HashPolicy) {
	*out = *in
	if in.Cookie != nil {
		in, out := &in.Cookie, &out.Cookie
		*out = new(CookieForHashing)
		**out = **in
	}
	if in.SourceIP != nil {
		in, out := &in.SourceIP, &out.SourceIP
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HashPolicy.
func (in *HashPolicy) DeepCopy() *HashPolicy {
	if in == nil {
		return nil
	}
	out := new(HashPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderMatcher) DeepCopyInto(out *HeaderMatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderMatcher.
func (in *HeaderMatcher) DeepCopy() *HeaderMatcher {
	if in == nil {
		return nil
	}
	out := new(HeaderMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheck) DeepCopyInto(out *HealthCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheck.
func (in *HealthCheck) DeepCopy() *HealthCheck {
	if in == nil {
		return nil
	}
	out := new(HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckList) DeepCopyInto(out *HealthCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HealthCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckList.
func (in *HealthCheckList) DeepCopy() *HealthCheckList {
	if in == nil {
		return nil
	}
	out := new(HealthCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckSpec) DeepCopyInto(out *HealthCheckSpec) {
	*out = *in
	if in.HTTPHealthCheck != nil {
		in, out := &in.HTTPHealthCheck, &out.HTTPHealthCheck
		*out = new(HTTPHealthCheckSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPHealthCheck != nil {
		in, out := &in.TCPHealthCheck, &out.TCPHealthCheck
		*out = new(TCPHealthCheckSpec)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(uint32)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(uint32)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(uint32)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(uint32)
		**out = **in
	}
	if in.JitterPercent != nil {
		in, out := &in.JitterPercent, &out.JitterPercent
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckSpec.
func (in *HealthCheckSpec) DeepCopy() *HealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(HealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckStatus) DeepCopyInto(out *HealthCheckStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckStatus.
func (in *HealthCheckStatus) DeepCopy() *HealthCheckStatus {
	if in == nil {
		return nil
	}
	out := new(HealthCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPMatcher) DeepCopyInto(out *IPMatcher) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPMatcher.
func (in *IPMatcher) DeepCopy() *IPMatcher {
	if in == nil {
		return nil
	}
	out := new(IPMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSChallengeConfig) DeepCopyInto(out *JSChallengeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSChallengeConfig.
func (in *JSChallengeConfig) DeepCopy() *JSChallengeConfig {
	if in == nil {
		return nil
	}
	out := new(JSChallengeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSInsertionRule) DeepCopyInto(out *JSInsertionRule) {
	*out = *in
	if in.ExcludedPaths != nil {
		in, out := &in.ExcludedPaths, &out.ExcludedPaths
		*out = make([]PathMatcher, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSInsertionRule.
func (in *JSInsertionRule) DeepCopy() *JSInsertionRule {
	if in == nil {
		return nil
	}
	out := new(JSInsertionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSInsertionRules) DeepCopyInto(out *JSInsertionRules) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]JSInsertionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSInsertionRules.
func (in *JSInsertionRules) DeepCopy() *JSInsertionRules {
	if in == nil {
		return nil
	}
	out := new(JSInsertionRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8SService) DeepCopyInto(out *K8SService) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
	if in.VirtualSite != nil {
		in, out := &in.VirtualSite, &out.VirtualSite
		*out = new(ObjectRef)
		**out = **in
	}
	if in.InsideNetwork != nil {
		in, out := &in.InsideNetwork, &out.InsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
	if in.OutsideNetwork != nil {
		in, out := &in.OutsideNetwork, &out.OutsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SService.
func (in *K8SService) DeepCopy() *K8SService {
	if in == nil {
		return nil
	}
	out := new(K8SService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelector) DeepCopyInto(out *LabelSelector) {
	*out = *in
	if in.Expressions != nil {
		in, out := &in.Expressions, &out.Expressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelector.
func (in *LabelSelector) DeepCopy() *LabelSelector {
	if in == nil {
		return nil
	}
	out := new(LabelSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPool) DeepCopyInto(out *OriginPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPool.
func (in *OriginPool) DeepCopy() *OriginPool {
	if in == nil {
		return nil
	}
	out := new(OriginPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OriginPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPoolList) DeepCopyInto(out *OriginPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OriginPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPoolList.
func (in *OriginPoolList) DeepCopy() *OriginPoolList {
	if in == nil {
		return nil
	}
	out := new(OriginPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OriginPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPoolSpec) DeepCopyInto(out *OriginPoolSpec) {
	*out = *in
	if in.OriginServers != nil {
		in, out := &in.OriginServers, &out.OriginServers
		*out = make([]OriginServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HealthChecks != nil {
		in, out := &in.HealthChecks, &out.HealthChecks
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
	if in.UseTLS != nil {
		in, out := &in.UseTLS, &out.UseTLS
		*out = new(OriginPoolTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.NoTLS != nil {
		in, out := &in.NoTLS, &out.NoTLS
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPoolSpec.
func (in *OriginPoolSpec) DeepCopy() *OriginPoolSpec {
	if in == nil {
		return nil
	}
	out := new(OriginPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPoolStatus) DeepCopyInto(out *OriginPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveredOrigins != nil {
		in, out := &in.DiscoveredOrigins, &out.DiscoveredOrigins
		*out = make([]DiscoveredOrigin, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPoolStatus.
func (in *OriginPoolStatus) DeepCopy() *OriginPoolStatus {
	if in == nil {
		return nil
	}
	out := new(OriginPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginPoolTLS) DeepCopyInto(out *OriginPoolTLS) {
	*out = *in
	if in.DefaultSecurity != nil {
		in, out := &in.DefaultSecurity, &out.DefaultSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.LowSecurity != nil {
		in, out := &in.LowSecurity, &out.LowSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.MediumSecurity != nil {
		in, out := &in.MediumSecurity, &out.MediumSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.CustomSecurity != nil {
		in, out := &in.CustomSecurity, &out.CustomSecurity
		*out = new(CustomTLSSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.VolterraTrustedCA != nil {
		in, out := &in.VolterraTrustedCA, &out.VolterraTrustedCA
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DisableSNI != nil {
		in, out := &in.DisableSNI, &out.DisableSNI
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UseServerVerification != nil {
		in, out := &in.UseServerVerification, &out.UseServerVerification
		*out = new(EmptyObject)
		**out = **in
	}
	if in.SkipServerVerification != nil {
		in, out := &in.SkipServerVerification, &out.SkipServerVerification
		*out = new(EmptyObject)
		**out = **in
	}
	if in.NoMTLS != nil {
		in, out := &in.NoMTLS, &out.NoMTLS
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginPoolTLS.
func (in *OriginPoolTLS) DeepCopy() *OriginPoolTLS {
	if in == nil {
		return nil
	}
	out := new(OriginPoolTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginServer) DeepCopyInto(out *OriginServer) {
	*out = *in
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(PublicIP)
		**out = **in
	}
	if in.PublicName != nil {
		in, out := &in.PublicName, &out.PublicName
		*out = new(PublicName)
		**out = **in
	}
	if in.PrivateIP != nil {
		in, out := &in.PrivateIP, &out.PrivateIP
		*out = new(PrivateIP)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateName != nil {
		in, out := &in.PrivateName, &out.PrivateName
		*out = new(PrivateName)
		(*in).DeepCopyInto(*out)
	}
	if in.K8SService != nil {
		in, out := &in.K8SService, &out.K8SService
		*out = new(K8SService)
		(*in).DeepCopyInto(*out)
	}
	if in.ConsulService != nil {
		in, out := &in.ConsulService, &out.ConsulService
		*out = new(ConsulService)
		(*in).DeepCopyInto(*out)
	}
	if in.Discover != nil {
		in, out := &in.Discover, &out.Discover
		*out = new(OriginServerDiscover)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginServer.
func (in *OriginServer) DeepCopy() *OriginServer {
	if in == nil {
		return nil
	}
	out := new(OriginServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginServerDiscover) DeepCopyInto(out *OriginServerDiscover) {
	*out = *in
	out.Resource = in.Resource
	if in.PortOverride != nil {
		in, out := &in.PortOverride, &out.PortOverride
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginServerDiscover.
func (in *OriginServerDiscover) DeepCopy() *OriginServerDiscover {
	if in == nil {
		return nil
	}
	out := new(OriginServerDiscover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathMatcher) DeepCopyInto(out *PathMatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathMatcher.
func (in *PathMatcher) DeepCopy() *PathMatcher {
	if in == nil {
		return nil
	}
	out := new(PathMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAllowDenyList) DeepCopyInto(out *PolicyAllowDenyList) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPPrefixSet != nil {
		in, out := &in.IPPrefixSet, &out.IPPrefixSet
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
	if in.ASNList != nil {
		in, out := &in.ASNList, &out.ASNList
		*out = new(ASNList)
		(*in).DeepCopyInto(*out)
	}
	if in.ASNSet != nil {
		in, out := &in.ASNSet, &out.ASNSet
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
	if in.CountryList != nil {
		in, out := &in.CountryList, &out.CountryList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultActionNextPolicy != nil {
		in, out := &in.DefaultActionNextPolicy, &out.DefaultActionNextPolicy
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DefaultActionDeny != nil {
		in, out := &in.DefaultActionDeny, &out.DefaultActionDeny
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DefaultActionAllow != nil {
		in, out := &in.DefaultActionAllow, &out.DefaultActionAllow
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAllowDenyList.
func (in *PolicyAllowDenyList) DeepCopy() *PolicyAllowDenyList {
	if in == nil {
		return nil
	}
	out := new(PolicyAllowDenyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBasedChallengeConfig) DeepCopyInto(out *PolicyBasedChallengeConfig) {
	*out = *in
	if in.DefaultJSChallengeParameters != nil {
		in, out := &in.DefaultJSChallengeParameters, &out.DefaultJSChallengeParameters
		*out = new(JSChallengeConfig)
		**out = **in
	}
	if in.DefaultCaptchaChallengeParameters != nil {
		in, out := &in.DefaultCaptchaChallengeParameters, &out.DefaultCaptchaChallengeParameters
		*out = new(CaptchaChallengeConfig)
		**out = **in
	}
	if in.DefaultMitigationSettings != nil {
		in, out := &in.DefaultMitigationSettings, &out.DefaultMitigationSettings
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AlwaysEnableJSChallenge != nil {
		in, out := &in.AlwaysEnableJSChallenge, &out.AlwaysEnableJSChallenge
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AlwaysEnableCaptcha != nil {
		in, out := &in.AlwaysEnableCaptcha, &out.AlwaysEnableCaptcha
		*out = new(EmptyObject)
		**out = **in
	}
	if in.NoChallenge != nil {
		in, out := &in.NoChallenge, &out.NoChallenge
		*out = new(EmptyObject)
		**out = **in
	}
	if in.MaliciousUserMitigationBypass != nil {
		in, out := &in.MaliciousUserMitigationBypass, &out.MaliciousUserMitigationBypass
		*out = new(EmptyObject)
		**out = **in
	}
	if in.RuleList != nil {
		in, out := &in.RuleList, &out.RuleList
		*out = new(ChallengeRuleList)
		(*in).DeepCopyInto(*out)
	}
	if in.TemporaryBlockingParameters != nil {
		in, out := &in.TemporaryBlockingParameters, &out.TemporaryBlockingParameters
		*out = new(TemporaryBlockingParams)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBasedChallengeConfig.
func (in *PolicyBasedChallengeConfig) DeepCopy() *PolicyBasedChallengeConfig {
	if in == nil {
		return nil
	}
	out := new(PolicyBasedChallengeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(PolicyRuleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRule.
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRuleList) DeepCopyInto(out *PolicyRuleList) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRuleList.
func (in *PolicyRuleList) DeepCopy() *PolicyRuleList {
	if in == nil {
		return nil
	}
	out := new(PolicyRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRuleSpec) DeepCopyInto(out *PolicyRuleSpec) {
	*out = *in
	if in.AnyClient != nil {
		in, out := &in.AnyClient, &out.AnyClient
		*out = new(EmptyObject)
		**out = **in
	}
	if in.ClientSelector != nil {
		in, out := &in.ClientSelector, &out.ClientSelector
		*out = new(LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IPMatcher != nil {
		in, out := &in.IPMatcher, &out.IPMatcher
		*out = new(IPMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.ASNMatcher != nil {
		in, out := &in.ASNMatcher, &out.ASNMatcher
		*out = new(ASNMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(PathMatcher)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]HeaderMatcher, len(*in))
		copy(*out, *in)
	}
	if in.HTTPMethod != nil {
		in, out := &in.HTTPMethod, &out.HTTPMethod
		*out = new(HTTPMethodMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRuleSpec.
func (in *PolicyRuleSpec) DeepCopy() *PolicyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateIP) DeepCopyInto(out *PrivateIP) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
	if in.VirtualSite != nil {
		in, out := &in.VirtualSite, &out.VirtualSite
		*out = new(ObjectRef)
		**out = **in
	}
	if in.InsideNetwork != nil {
		in, out := &in.InsideNetwork, &out.InsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
	if in.OutsideNetwork != nil {
		in, out := &in.OutsideNetwork, &out.OutsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateIP.
func (in *PrivateIP) DeepCopy() *PrivateIP {
	if in == nil {
		return nil
	}
	out := new(PrivateIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateName) DeepCopyInto(out *PrivateName) {
	*out = *in
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(ObjectRef)
		**out = **in
	}
	if in.VirtualSite != nil {
		in, out := &in.VirtualSite, &out.VirtualSite
		*out = new(ObjectRef)
		**out = **in
	}
	if in.InsideNetwork != nil {
		in, out := &in.InsideNetwork, &out.InsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
	if in.OutsideNetwork != nil {
		in, out := &in.OutsideNetwork, &out.OutsideNetwork
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateName.
func (in *PrivateName) DeepCopy() *PrivateName {
	if in == nil {
		return nil
	}
	out := new(PrivateName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedAppEndpoint) DeepCopyInto(out *ProtectedAppEndpoint) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HTTPMethods != nil {
		in, out := &in.HTTPMethods, &out.HTTPMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Path = in.Path
	if in.AnyDomain != nil {
		in, out := &in.AnyDomain, &out.AnyDomain
		*out = new(EmptyObject)
		**out = **in
	}
	if in.MitigationAction != nil {
		in, out := &in.MitigationAction, &out.MitigationAction
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedAppEndpoint.
func (in *ProtectedAppEndpoint) DeepCopy() *ProtectedAppEndpoint {
	if in == nil {
		return nil
	}
	out := new(ProtectedAppEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicIP) DeepCopyInto(out *PublicIP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicIP.
func (in *PublicIP) DeepCopy() *PublicIP {
	if in == nil {
		return nil
	}
	out := new(PublicIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicName) DeepCopyInto(out *PublicName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicName.
func (in *PublicName) DeepCopy() *PublicName {
	if in == nil {
		return nil
	}
	out := new(PublicName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
	if in.RateLimiter != nil {
		in, out := &in.RateLimiter, &out.RateLimiter
		*out = new(RateLimiterInline)
		**out = **in
	}
	if in.NoIPAllowedList != nil {
		in, out := &in.NoIPAllowedList, &out.NoIPAllowedList
		*out = new(EmptyObject)
		**out = **in
	}
	if in.IPAllowedList != nil {
		in, out := &in.IPAllowedList, &out.IPAllowedList
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
	if in.NoPolicies != nil {
		in, out := &in.NoPolicies, &out.NoPolicies
		*out = new(EmptyObject)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(RateLimitPolicies)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitPolicies) DeepCopyInto(out *RateLimitPolicies) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicies.
func (in *RateLimitPolicies) DeepCopy() *RateLimitPolicies {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiter) DeepCopyInto(out *RateLimiter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiter.
func (in *RateLimiter) DeepCopy() *RateLimiter {
	if in == nil {
		return nil
	}
	out := new(RateLimiter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimiter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterInline) DeepCopyInto(out *RateLimiterInline) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterInline.
func (in *RateLimiterInline) DeepCopy() *RateLimiterInline {
	if in == nil {
		return nil
	}
	out := new(RateLimiterInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterList) DeepCopyInto(out *RateLimiterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RateLimiter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterList.
func (in *RateLimiterList) DeepCopy() *RateLimiterList {
	if in == nil {
		return nil
	}
	out := new(RateLimiterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimiterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterSpec) DeepCopyInto(out *RateLimiterSpec) {
	*out = *in
	if in.BurstMultiplier != nil {
		in, out := &in.BurstMultiplier, &out.BurstMultiplier
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterSpec.
func (in *RateLimiterSpec) DeepCopy() *RateLimiterSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimiterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterStatus) DeepCopyInto(out *RateLimiterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterStatus.
func (in *RateLimiterStatus) DeepCopy() *RateLimiterStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimiterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RingHashConfig) DeepCopyInto(out *RingHashConfig) {
	*out = *in
	if in.HashPolicy != nil {
		in, out := &in.HashPolicy, &out.HashPolicy
		*out = make([]HashPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RingHashConfig.
func (in *RingHashConfig) DeepCopy() *RingHashConfig {
	if in == nil {
		return nil
	}
	out := new(RingHashConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutePool) DeepCopyInto(out *RoutePool) {
	*out = *in
	out.Pool = in.Pool
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(uint32)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutePool.
func (in *RoutePool) DeepCopy() *RoutePool {
	if in == nil {
		return nil
	}
	out := new(RoutePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensitiveDataDetectionRules) DeepCopyInto(out *SensitiveDataDetectionRules) {
	*out = *in
	if in.SensitiveDataTypes != nil {
		in, out := &in.SensitiveDataTypes, &out.SensitiveDataTypes
		*out = make([]SensitiveDataType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensitiveDataDetectionRules.
func (in *SensitiveDataDetectionRules) DeepCopy() *SensitiveDataDetectionRules {
	if in == nil {
		return nil
	}
	out := new(SensitiveDataDetectionRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensitiveDataType) DeepCopyInto(out *SensitiveDataType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensitiveDataType.
func (in *SensitiveDataType) DeepCopy() *SensitiveDataType {
	if in == nil {
		return nil
	}
	out := new(SensitiveDataType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerNameMatcher) DeepCopyInto(out *ServerNameMatcher) {
	*out = *in
	if in.ExactValues != nil {
		in, out := &in.ExactValues, &out.ExactValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegexValues != nil {
		in, out := &in.RegexValues, &out.RegexValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerNameMatcher.
func (in *ServerNameMatcher) DeepCopy() *ServerNameMatcher {
	if in == nil {
		return nil
	}
	out := new(ServerNameMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSelector) DeepCopyInto(out *ServerSelector) {
	*out = *in
	if in.Expressions != nil {
		in, out := &in.Expressions, &out.Expressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSelector.
func (in *ServerSelector) DeepCopy() *ServerSelector {
	if in == nil {
		return nil
	}
	out := new(ServerSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicy) DeepCopyInto(out *ServicePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicy.
func (in *ServicePolicy) DeepCopy() *ServicePolicy {
	if in == nil {
		return nil
	}
	out := new(ServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServicePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicyList) DeepCopyInto(out *ServicePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServicePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicyList.
func (in *ServicePolicyList) DeepCopy() *ServicePolicyList {
	if in == nil {
		return nil
	}
	out := new(ServicePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServicePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicySpec) DeepCopyInto(out *ServicePolicySpec) {
	*out = *in
	if in.AllowAllRequests != nil {
		in, out := &in.AllowAllRequests, &out.AllowAllRequests
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AllowList != nil {
		in, out := &in.AllowList, &out.AllowList
		*out = new(PolicyAllowDenyList)
		(*in).DeepCopyInto(*out)
	}
	if in.DenyAllRequests != nil {
		in, out := &in.DenyAllRequests, &out.DenyAllRequests
		*out = new(EmptyObject)
		**out = **in
	}
	if in.DenyList != nil {
		in, out := &in.DenyList, &out.DenyList
		*out = new(PolicyAllowDenyList)
		(*in).DeepCopyInto(*out)
	}
	if in.RuleList != nil {
		in, out := &in.RuleList, &out.RuleList
		*out = new(PolicyRuleList)
		(*in).DeepCopyInto(*out)
	}
	if in.AnyServer != nil {
		in, out := &in.AnyServer, &out.AnyServer
		*out = new(EmptyObject)
		**out = **in
	}
	if in.ServerNameMatcher != nil {
		in, out := &in.ServerNameMatcher, &out.ServerNameMatcher
		*out = new(ServerNameMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerSelector != nil {
		in, out := &in.ServerSelector, &out.ServerSelector
		*out = new(ServerSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicySpec.
func (in *ServicePolicySpec) DeepCopy() *ServicePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ServicePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicyStatus) DeepCopyInto(out *ServicePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicyStatus.
func (in *ServicePolicyStatus) DeepCopy() *ServicePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ServicePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignatureSelectionSetting) DeepCopyInto(out *SignatureSelectionSetting) {
	*out = *in
	if in.DefaultAttackTypeSettings != nil {
		in, out := &in.DefaultAttackTypeSettings, &out.DefaultAttackTypeSettings
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AttackTypeSettings != nil {
		in, out := &in.AttackTypeSettings, &out.AttackTypeSettings
		*out = new(AttackTypeSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.HighMediumLowAccuracySignatures != nil {
		in, out := &in.HighMediumLowAccuracySignatures, &out.HighMediumLowAccuracySignatures
		*out = new(EmptyObject)
		**out = **in
	}
	if in.HighMediumAccuracySignatures != nil {
		in, out := &in.HighMediumAccuracySignatures, &out.HighMediumAccuracySignatures
		*out = new(EmptyObject)
		**out = **in
	}
	if in.OnlyHighAccuracySignatures != nil {
		in, out := &in.OnlyHighAccuracySignatures, &out.OnlyHighAccuracySignatures
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignatureSelectionSetting.
func (in *SignatureSelectionSetting) DeepCopy() *SignatureSelectionSetting {
	if in == nil {
		return nil
	}
	out := new(SignatureSelectionSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPHealthCheckSpec) DeepCopyInto(out *TCPHealthCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPHealthCheckSpec.
func (in *TCPHealthCheckSpec) DeepCopy() *TCPHealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(TCPHealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPLoadBalancer) DeepCopyInto(out *TCPLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPLoadBalancer.
func (in *TCPLoadBalancer) DeepCopy() *TCPLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(TCPLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPLoadBalancerList) DeepCopyInto(out *TCPLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCPLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPLoadBalancerList.
func (in *TCPLoadBalancerList) DeepCopy() *TCPLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(TCPLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPLoadBalancerSpec) DeepCopyInto(out *TCPLoadBalancerSpec) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OriginPools != nil {
		in, out := &in.OriginPools, &out.OriginPools
		*out = make([]RoutePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NoTLS != nil {
		in, out := &in.NoTLS, &out.NoTLS
		*out = new(EmptyObject)
		**out = **in
	}
	if in.TLSParameters != nil {
		in, out := &in.TLSParameters, &out.TLSParameters
		*out = new(TLSParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSTCPAutoCert != nil {
		in, out := &in.TLSTCPAutoCert, &out.TLSTCPAutoCert
		*out = new(TLSTCPAutoCert)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvertiseOnPublicDefaultVIP != nil {
		in, out := &in.AdvertiseOnPublicDefaultVIP, &out.AdvertiseOnPublicDefaultVIP
		*out = new(EmptyObject)
		**out = **in
	}
	if in.AdvertiseOnPublic != nil {
		in, out := &in.AdvertiseOnPublic, &out.AdvertiseOnPublic
		*out = new(AdvertiseOnPublic)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvertiseCustom != nil {
		in, out := &in.AdvertiseCustom, &out.AdvertiseCustom
		*out = new(AdvertiseCustom)
		(*in).DeepCopyInto(*out)
	}
	if in.DoNotAdvertise != nil {
		in, out := &in.DoNotAdvertise, &out.DoNotAdvertise
		*out = new(EmptyObject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPLoadBalancerSpec.
func (in *TCPLoadBalancerSpec) DeepCopy() *TCPLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(TCPLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPLoadBalancerStatus) DeepCopyInto(out *TCPLoadBalancerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPLoadBalancerStatus.
func (in *TCPLoadBalancerStatus) DeepCopy() *TCPLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(TCPLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSCertificateRef) DeepCopyInto(out *TLSCertificateRef) {
	*out = *in
	in.PrivateKey.DeepCopyInto(&out.PrivateKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSCertificateRef.
func (in *TLSCertificateRef) DeepCopy() *TLSCertificateRef {
	if in == nil {
		return nil
	}
	out := new(TLSCertificateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSParameters) DeepCopyInto(out *TLSParameters) {
	*out = *in
	if in.TLSCertificates != nil {
		in, out := &in.TLSCertificates, &out.TLSCertificates
		*out = make([]TLSCertificateRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultSecurity != nil {
		in, out := &in.DefaultSecurity, &out.DefaultSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.LowSecurity != nil {
		in, out := &in.LowSecurity, &out.LowSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.MediumSecurity != nil {
		in, out := &in.MediumSecurity, &out.MediumSecurity
		*out = new(EmptyObject)
		**out = **in
	}
	if in.CustomSecurity != nil {
		in, out := &in.CustomSecurity, &out.CustomSecurity
		*out = new(CustomTLSSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.NoMTLS != nil {
		in, out := &in.NoMTLS, &out.NoMTLS
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UseMTLS != nil {
		in, out := &in.UseMTLS, &out.UseMTLS
		*out = new(UseMTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSParameters.
func (in *TLSParameters) DeepCopy() *TLSParameters {
	if in == nil {
		return nil
	}
	out := new(TLSParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSTCPAutoCert) DeepCopyInto(out *TLSTCPAutoCert) {
	*out = *in
	if in.NoMTLS != nil {
		in, out := &in.NoMTLS, &out.NoMTLS
		*out = new(EmptyObject)
		**out = **in
	}
	if in.UseMTLS != nil {
		in, out := &in.UseMTLS, &out.UseMTLS
		*out = new(UseMTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSTCPAutoCert.
func (in *TLSTCPAutoCert) DeepCopy() *TLSTCPAutoCert {
	if in == nil {
		return nil
	}
	out := new(TLSTCPAutoCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporaryBlockingParams) DeepCopyInto(out *TemporaryBlockingParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporaryBlockingParams.
func (in *TemporaryBlockingParams) DeepCopy() *TemporaryBlockingParams {
	if in == nil {
		return nil
	}
	out := new(TemporaryBlockingParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UseMTLS) DeepCopyInto(out *UseMTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UseMTLS.
func (in *UseMTLS) DeepCopy() *UseMTLS {
	if in == nil {
		return nil
	}
	out := new(UseMTLS)
	in.DeepCopyInto(out)
	return out
}
