apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: f5xc-k8s-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
